### ISSUE TITLE
So it use redis or postgresql

### ISSUE THREAD

**Issue by rostykk** [vams-app/onair-discordbot#1]
i get error about which is not in config at all

```
@prisma\client\runtime\index.js:34316
      throw new PrismaClientInitializationError(message, this.client._clientVersion);
            ^

PrismaClientInitializationError:
Invalid `this.Model.upsert()` invocation in
_redacted_\onair-discordbot\repos\VirtualAirlineRepo.js:95:33

  92     include: (opts?.include) ? opts.include : undefined,
  93 }
  94
→ 95 return await this.Model.upsert(
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   |
 9 |   provider = "postgresql"
10 |   url      = env("DATABASE_URL")
```
   |

**Comment by mikedevita** [comment]
Hi, apologies, I didn't realize that You created this issue 😂. The current master branch has a few tweaks needed to get things working but to answer your question, the bot uses both Redis and Postgres.

Postgres is to store the data fetched from OnAir and to associate a Discord User to their OnAir company.

The plan was to use Redis for event queue handling from external services that I built for my Virtual Airline that will notify the bot to do some action, e.g.; send a discord message to a channel that a flight has landed or departed but I am not sure that's the best route to go anymore.

That being said, I am working on the codebase now and will get it up to par to be able to be running without much fuss along with some documentation/steps to get it going. For now, I am going to close this ticket but I will mention the issue when its fixed so you will get notified.

**Comment by mikedevita** [comment]
Hi, apologies, I didn't realize that You created this issue 😂. The current master branch has a few tweaks needed to get things working but to answer your question, the bot uses both Redis and Postgres.

Postgres is to store the data fetched from OnAir and to associate a Discord User to their OnAir company.

The plan was to use Redis for event queue handling from external services that I built for my Virtual Airline that will notify the bot to do some action, e.g.; send a discord message to a channel that a flight has landed or departed but I am not sure that's the best route to go anymore.

That being said, I am working on the codebase now and will get it up to par to be able to be running without much fuss along with some documentation/steps to get it going. For now, I am going to close this ticket but I will mention the issue when its fixed so you will get notified.

**Comment by mikedevita** [comment]
Alright, I think i've worked through the bugs. Please re-clone the repository and try again. Redis is not needed at this point.
